name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20.x
      - name: Install dependencies in production
        run: npm ci --ignore-scripts
      - name: Cache next.js build
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: .next/
          key: ${{ runner.os }}-next-build-${{ hashFiles('src/','public/','next*','package*','jsconfig.json') }}
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Build the app
        continue-on-error: true
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Just Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.APP_IMAGE }}
          file: ./Dockerfile
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
